// <auto-generated />
using System;
using InventarioFarmacia_Back;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventarioFarmacia_Back.Migrations
{
    [DbContext(typeof(PharmDBContext))]
    [Migration("20251003033227_VainaDeInvenatrios")]
    partial class VainaDeInvenatrios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Bitacora_Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha_Actualizacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_Inventario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_Accion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id_Inventario")
                        .HasDatabaseName("IX_Bitacora_Inventarios_Id_Inventario");

                    b.HasIndex("Id_Usuario");

                    b.HasIndex("InventarioId");

                    b.ToTable("Bitacora_Inventarios");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Bitacora_Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Campo_Modificado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_Cambio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_Producto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor_Anterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor_Nuevo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id_Producto")
                        .HasDatabaseName("IX_Bitacora_Productos_Id_Producto");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Bitacora_Productos");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icono")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Detalle_Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_Producto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Venta")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id_Producto");

                    b.HasIndex("Id_Venta")
                        .HasDatabaseName("IX_Detalle_Ventas_Id_Venta");

                    b.ToTable("Detalle_Ventas");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Ultima_Actualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha_Vencimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_Producto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nro_Lote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id_Producto");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Orden_Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha_Pedido")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha_Recibo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orden_Compras");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Existencias_Por_Caja")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_Clinico")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio_Caja")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio_Unitario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruta_Imagen")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tiene_Subunidades")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Unidades_Por_Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id_Categoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Producto_Individual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Inventario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Lote")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_OrdenCompra")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id_Inventario");

                    b.HasIndex("Id_Lote")
                        .HasDatabaseName("IX_Productos_Individuales_Nro_Lote");

                    b.HasIndex("Id_OrdenCompra");

                    b.ToTable("Productos_Individuales");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad_Productos")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo_Total")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha_Venta")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Id_Usuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("InventarioLote", b =>
                {
                    b.Property<int>("InventariosId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LotesDeProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InventariosId", "LotesDeProductoId");

                    b.HasIndex("LotesDeProductoId");

                    b.ToTable("InventarioLote", (string)null);
                });

            modelBuilder.Entity("LoteOrden_Compra", b =>
                {
                    b.Property<int>("LotesInvolucradosId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdenesCompraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LotesInvolucradosId", "OrdenesCompraId");

                    b.HasIndex("OrdenesCompraId");

                    b.ToTable("OrdenCompraLote", (string)null);
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Bitacora_Inventario", b =>
                {
                    b.HasOne("InventarioFarmacia_Domain.Models.Inventario", null)
                        .WithMany("BitacoraInventarios")
                        .HasForeignKey("Id_Inventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioFarmacia_Domain.Models.Usuario", null)
                        .WithMany("BitacoraInventarios")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("InventarioFarmacia_Domain.Models.Inventario", "Inventario")
                        .WithMany()
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Bitacora_Producto", b =>
                {
                    b.HasOne("InventarioFarmacia_Domain.Models.Producto", null)
                        .WithMany("BitacoraProductos")
                        .HasForeignKey("Id_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioFarmacia_Domain.Models.Usuario", null)
                        .WithMany("BitacoraProductos")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Detalle_Venta", b =>
                {
                    b.HasOne("InventarioFarmacia_Domain.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Id_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioFarmacia_Domain.Models.Venta", "Venta")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("Id_Venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Lote", b =>
                {
                    b.HasOne("InventarioFarmacia_Domain.Models.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("Id_Producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Producto", b =>
                {
                    b.HasOne("InventarioFarmacia_Domain.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("Id_Categoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Producto_Individual", b =>
                {
                    b.HasOne("InventarioFarmacia_Domain.Models.Inventario", null)
                        .WithMany()
                        .HasForeignKey("Id_Inventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioFarmacia_Domain.Models.Lote", null)
                        .WithMany("ProductosIndividuales")
                        .HasForeignKey("Id_Lote")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("InventarioFarmacia_Domain.Models.Orden_Compra", null)
                        .WithMany()
                        .HasForeignKey("Id_OrdenCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Venta", b =>
                {
                    b.HasOne("InventarioFarmacia_Domain.Models.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("InventarioLote", b =>
                {
                    b.HasOne("InventarioFarmacia_Domain.Models.Inventario", null)
                        .WithMany()
                        .HasForeignKey("InventariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioFarmacia_Domain.Models.Lote", null)
                        .WithMany()
                        .HasForeignKey("LotesDeProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoteOrden_Compra", b =>
                {
                    b.HasOne("InventarioFarmacia_Domain.Models.Lote", null)
                        .WithMany()
                        .HasForeignKey("LotesInvolucradosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioFarmacia_Domain.Models.Orden_Compra", null)
                        .WithMany()
                        .HasForeignKey("OrdenesCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Inventario", b =>
                {
                    b.Navigation("BitacoraInventarios");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Lote", b =>
                {
                    b.Navigation("ProductosIndividuales");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Producto", b =>
                {
                    b.Navigation("BitacoraProductos");

                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Usuario", b =>
                {
                    b.Navigation("BitacoraInventarios");

                    b.Navigation("BitacoraProductos");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("InventarioFarmacia_Domain.Models.Venta", b =>
                {
                    b.Navigation("DetalleVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
